apiVersion: 1
datasources:
  - name: QuestDB
    type: questdb-questdb-datasource
    uid: 2Bi8EToVz 
    jsonData:
      server: host.docker.internal
      port: 8812
      username: admin
      tlsMode: disable
      # timeout: <seconds>
      # queryTimeout: <seconds>
      maxOpenConnections: 100
      maxIdleConnections: 100
      maxConnectionLifetime: 14400
    secureJsonData:
      password: ${GRAFANA_QUESTDB_PASSWORD}
      # tlsCACert: <string>  